version: '3.2'

services:
  db:
   build:
     context: ./db
     dockerfile: Dockerfile
   restart: always
   environment: 
     - POSTGRES_DB=rightprism
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - "5432:5432"
   volumes:
    - ./var/lib/postgresql/data
   networks:
     rpnet:
       ipv4_address: 152.28.1.3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RP_ENV=dev
      - DB_NAME=rightprism
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=152.28.1.3
      - DB_PORT=5432
    ports:
      - "8080:8080"
    networks:
      rpnet:
        ipv4_address: 152.28.1.2
    depends_on:
      - db

networks:
  rpnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 152.28.0.0/16
